### ISSUE TITLE
Contributing codes

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#102]
Hi there!
I would like to publish how-to codes for Pandas, Numpy, PyTorch, Plotly, etc., which are simpler and easier to understand compared to the documentation.

2 options:
- Create a new folder within uni-notes
   (I prefer this approach as it would be easier to maintain)
- Should I make a new repo for it?
   (maintaining the same mkdocs settings and other features like a potential comment-box would be too hard)

**Comment by Fir121** [comment]
Well it is relevant for Uni students so it can be nice as part of this same repository under a new heading, you already have users for uni-notes so that way it can benefit students.

If you were to make a new repo you can push it to a new audience but I like the idea of using uni-notes itself.

**Comment by AhmedThahir** [comment]
Alright great! I will start working on the contributing to the same repo :)

Any suggestions on the folder name?
*Tools*

So the navigation would be like:
- Tools/Pytorch
- Tools/Sklearn
- ...

**Comment by ysh1th** [comment]
I feel _CS Tools_ would be more accurate or more specifically...
_Data Science Tools_ if the focus is on such of them.

**Comment by AhmedThahir** [comment]
Hmm, tools like script & pytorch would come under optimization and data science. I'm hoping that students can't contribute about tools like Ansysn simulation etc also here. 

So, I'm thinking for now I'll keep it in a generic folder name and later we can decide to/not to further classify tools.

**Comment by ysh1th** [comment]
Sounds good

**Comment by Fir121** [comment]
Closing as it is done
