### ISSUE TITLE
Broken links in the documents

### ISSUE THREAD

**Issue by ysh1th** [uni-notes/uni-notes#110]
### Project Contribution

- [X] I have read and agree to the project's [Contribution Guidelines](https://github.com/unnamed-project/.github/CODE_OF_CONDUCT.md)📜

### What happened?

Here is a list of broken links I've found in the notes that are needed to be resolved:

- [ ] [1_Core/Technical_Report_Writing/03_Sample_Report_&_Slides/#sample-report-and-slides](https://uni-notes.netlify.app/1_Core/Technical_Report_Writing/03_Sample_Report_%26_Slides/#sample-report-and-slides) contains a relative link 'assets/CyberSecurity_Report.pdf', but the target '1_Core/Technical_Report_Writing/assets/CyberSecurity_Report.pdf' is not found among documentation files
- [ ] [1_Core/Technical_Report_Writing/03_Sample_Report_&_Slides/#sample-report-and-slides](https://github.com/uni-notes/uni-notes/edit/main/docs/1_Core/Technical_Report_Writing/03_Sample_Report_&_Slides.md) contains a relative link 'assets/CyberSecurity_Slides.pdf', but the target '1_Core/Technical_Report_Writing/assets/CyberSecurity_Slides.pdf' is not found among documentation files
- [ ] [1_Core/Technical_Report_Writing/03_Sample_Report_&_Slides/#sample-report-and-slides](https://github.com/uni-notes/uni-notes/edit/main/docs/1_Core/Technical_Report_Writing/03_Sample_Report_&_Slides.md) contains a relative link 'assets/Web_Report.pdf', but the target '1_Core/Technical_Report_Writing/assets/Web_Report.pdf' is not found among documentation files
- [ ] [2_Core/Math_3/02_Exact_DE/#family-of-curves](https://uni-notes.netlify.app/2_Core/Math_3/02_Exact_DE/#family-of-curves) contains a relative link in incorrect format '01 Intro#Homogeneous Equation'
- [ ] [2_Core/MicroProcessors_&_Interfacing/01_Intro.md](https://uni-notes.netlify.app/2_core/microprocessors_&_interfacing/01_intro/#nehas-notes) contains a relative link 'assets/neha.pdf', but the target '2_Core/MicroProcessors_&_Interfacing/assets/neha.pdf' is not found among documentation files
- [ ] [2_Core/MicroProcessors_&_Interfacing/11_Pin_Out_Control_Data/#bi-directional-buffer](https://uni-notes.netlify.app/2_core/microprocessors_&_interfacing/11_pin_out_control_data/#bi-directional-buffer) contains incorrect format of link '\(\overline{DEN}\)'
- [ ] [2_Core/MicroProcessors_&_Interfacing/11_Pin_Out_Control_Data.md](https://uni-notes.netlify.app/2_core/microprocessors_&_interfacing/11_pin_out_control_data/#dir) contains an absolute link '\(DT/\overline{R}\)'
- [ ] [3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler](https://uni-notes.netlify.app/3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler) contains a relative link '04_Semantic_Analysis.md', but the target '3_Core/Compiler_Contruction/04_Semantic_Analysis.md' is not found - incorrect target address specified
- [ ] [3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler](https://uni-notes.netlify.app/3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler) contains a relative link '04_Semantic_Analysis.md#coercions', but the target '3_Core/Compiler_Contruction/04_Semantic_Analysis.md' is not found among documentation files - same incorrect target address specified
- [ ] [3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler](https://uni-notes.netlify.app/3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler) contains a relative link '05_Intermediate_Code_Generation.md', but the target '3_Core/Compiler_Contruction/05_Intermediate_Code_Generation.md' is not found among documentation files.
- [ ] [3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler](https://uni-notes.netlify.app/3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler) contains a relative link '06_Code_Optimization.md', but the target '3_Core/Compiler_Contruction/06_Code_Optimization.md' is not found among documentation files
- [ ] [3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler](https://uni-notes.netlify.app/3_Core/Compiler_Contruction/01_Introduction/#stages-of-compiler) contains a relative link '07_Code_Generation.md', but the target '3_Core/Compiler_Contruction/07_Code_Generation.md' is not found among documentation files.
- [ ] ['3_Core/Compiler_Contruction/03_Syntax_Analysis/#yacc'](https://uni-notes.netlify.app/3_Core/Compiler_Contruction/03_Syntax_Analysis/#yacc) contains incorrect link format - './practicals/'
- [ ] [3_Core/Compiler_Contruction/03_Syntax_Analysis/#tool-provided-disambiguation](https://uni-notes.netlify.app/3_Core/Compiler_Contruction/03_Syntax_Analysis/#tool-provided-disambiguation) contains incorrect link format - './practicals/' like above point
- [ ] [3_Core/Compiler_Contruction/03_Syntax_Analysis/#shift-reduce-parsing](https://uni-notes.netlify.app/3_core/compiler_contruction/03_syntax_analysis/#shift-reduce-parsing) contains a relative link 'Practical/06_Yacc_Directives.md', but the target '3_Core/Compiler_Contruction/Practical/06_Yacc_Directives.md' is not found among documentation files
- [ ] [3_core/computer_networks/08_ethernet/#example-of-multiple-frames](https://uni-notes.netlify.app/3_core/computer_networks/08_ethernet/#example-of-multiple-frames) contains a relative link 'assets/ethernet_frame.svg', but the target '3_Core/Computer_Networks/assets/ethernet_frame.svg' is not found among documentation files
- [ ] ['3_Core/Operating_Systems/01_Intro/#lab-code'](https://uni-notes.netlify.app/3_core/operating_systems/01_intro/#lab-code) contains incorrect relative link to 'Lab'
- [ ] [ 'CS_Electives/Deep_Learning/01_Introduction.md'](https://uni-notes.netlify.app/CS_Electives/Deep_Learning/01_Introduction/) contains incorrect target address to './../Machine_Learning/'
- [ ] ['CS_Electives/Deep_Learning/02_ANN.md' ](https://uni-notes.netlify.app/CS_Electives/Deep_Learning/02_ANN/) contains incorrect target address './../Deep_Learning/'
- [ ] ['CS_Electives/Machine_Learning/08_classification/#classifcation-accuracy-measures'](https://uni-notes.netlify.app/cs_electives/machine_learning/08_classification/#classifcation-accuracy-measures) contains a relative link '../Data_Mining/07_Classification.md#Classification Accuracy Metrics', but the target 'CS_Electives/Data_Mining/07_Classification.md' is not found among documentation files
- [ ] [Finance_Electives/Revenue_Optimization/01_Introduction/#optimization](https://uni-notes.netlify.app/Finance_Electives/Revenue_Optimization/01_Introduction/#optimization) has incorrect target address { to be replaced with (Math_Electives/Optimization/)

**Comment by AhmedThahir** [comment]
Thanks a lot for bringing this, and nicely formatting it as a task list :)

**Comment by AhmedThahir** [comment]
Seems like a lot of work to fix right now; closing as low priority
