### ISSUE TITLE
Error in Git Committers Plugin

### ISSUE THREAD

**Issue by Fir121** [uni-notes/uni-notes#111]
### Project Contribution

- [X] I have read and agree to the project's [Contribution Guidelines](https://github.com/unnamed-project/.github/CODE_OF_CONDUCT.md)📜

### What happened?

Error Occurring during netlify build

8:41:39 PM: ERROR   -  git-committers:   403 rate limit exceeded - You may have exceeded the API rate limit or need to be authorized. You can set a token under "token" mkdocs.yml config or MKDOCS_GIT_COMMITTERS_APIKEY environment variable.

### Anything Else🤔?

Should be a simple fix. Add the token variable as specified in the error, this can be experimented locally, see if you need to add a secrets file in the deployment.

**Comment by AhmedThahir** [comment]
What do you suggest is the best way to proceed here?

**Comment by Fir121** [comment]
Best way would be to deploy directly from gh-pages branch. Any errors here can happen in netlify too, if anything, github is more reliable. BUT please check how deploy previews work, if I am not mistaken doing this will disable deploy preview, if that is the trade off I'd rather you keep it as it is.

We can fix this bug in some other way.

**Comment by AhmedThahir** [comment]
Is this fixed?

**Comment by Fir121** [comment]
Yup
