### ISSUE TITLE
Uni-Notes Description for BITS Pilani Newsletter

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#114]
I'm thinking of sharing this. Please help me with the benefits.

---

Hi there, students!

**The Interesting Bits**
📝 New semester started? Find notes from top students and join the growing free and open-source initiative, with topics ranging from CS, Math, Finance, and so much more. We're actively looking for more contributors as well!

👇 Click here to install the app now! All the best for your semester :)
[uni-notes.netlify.app](https://uni-notes.netlify.app/)

**Benefits**
- Unified source of resources compiled by the BITS community
- Light-weight app with auto-save of visited pages for offline-use
- Fully-searchable
- Discussions module supported for Q&A and other student interactions
- Open-sourcing encourages continuous updates, using Git that ensures a seamless experience for contributors

[![uni-notes](https://github.com/uni-notes/uni-notes/assets/94914628/a849a362-df54-4954-bd4f-8a7e4215a0dd)](https://uni-notes.netlify.app/)

**The Boring Bytes**
**How it started**
When Ahmed Thahir started out at university, there were no clear cut resources to prepare for exams. It was very cluttered and everyone was giving contradictory advice on how to prepare. That's when he decided to start an open-source initiative to solve this issue.

After initially starting out with typed out PDFs uploaded on Google Drive, he received tremendous appreciation, but wanted to take it to the next level: in a way that collaboration and contributions are possible; something like Wikipedia, but nicer :) He contacted a couple of students interested in the initiative and opened up a GitHub repository, with major contributions from Mohamed Firas Adil in terms of developing & deploying the web app.

We already have many contributors/users, so we look forward to hearing your feedback. Feel free to contact any of us for any questions, preferably on GitHub.

**Testimonials**

**Bhavya Kothari (User; 3rd Year CS @ BPDC)**

> Uni Notes is seriously a saviour for those drowning in the sea of study materials. Picture this – all your notes and resources piled up in one cozy corner, thanks to the awesome BITS community. 
> 
> Now, here's a real usecase – it's a game-changer for classes where class participation is an evaluation component. You know those courses where you gotta talk the talk during discussions? Uni Notes has your back. Reading up beforehand is a breeze, and trust me, it's a game-changer. And let's not even talk about those days you miss class, and you're stuck with a jigsaw puzzle of your friend's notes. Uni Notes is the ultimate time-saver. No more matching up scrambled photos – just smooth sailing through your course materials. It's like having a personal study wizard. Give it a shot, thank me later!

**Yashwanth Karuparthi (Contributor; 3rd Year CS @ BPDC)**

> It's not often you get to collaborate with brilliant friends and contribute to something awesome made for the student universe, and I'm thrilled to have been a part of its inception.
> 
> As a first contributor, from fixing LaTeX formatting to refining our contribution workflow on Github, the process has been incredibly straightforward and was a learning experience like no other. The welcoming atmosphere and clear guidelines make it easy for anyone, regardless of experience level, to jump in and make a difference. And not to forget the satisfaction when your contribution gets accepted and integrated into the project.
> 
> It's inspiring to see how a group of passionate individuals can come together to create something truly impactful. So, if you've ever thought about contributing to an open-source project, don't hesitate—Uni-notes is the perfect place to start your journey!

👇 Still haven't installed? Click now to join the initiative!
[uni-notes.netlify.app](https://uni-notes.netlify.app/)

Best Regards,
Uni-Notes team

**Comment by Fir121** [comment]
Benefits (written in short)

- Single source of notes and resources compiled by the BITS community

- Open sourced to ensure it stays up to date and keeps improving. Using technologies that makes it easy to contribute changes and additions.

- Quick and easy to use interface eliminating hassles of loading and searching for the right notes.


There is no technical explanation in the writeup, that's for the best right? 

And I was thinking if including a testimonial or two might be nice?

**Comment by AhmedThahir** [comment]
Yepppp you're right.

Any idea who we can ask?

**Comment by Fir121** [comment]
@ysh1th would you be interested in writing a testimonial as a contributor+user

As for user testimonials I know a few - I'll ask around and let you know. We can collate a few options and let the newsletter team pick any if they want.

**Comment by Fir121** [comment]
@bruhvya would you write a small testimonial on how this has been useful for you

**Comment by ysh1th** [comment]
> @ysh1th would you be interested in writing a testimonial as a contributor+user
> 
> As for user testimonials I know a few - I'll ask around and let you know. We can collate a few options and let the newsletter team pick any if they want.



It's not often you get to collaborate with brilliant friends and contribute to something awesome made for the student universe, and I'm thrilled to have been a part of its inception.

As a first contributor, from fixing LaTeX formatting to refining our contribution workflow on Github, the process has been incredibly straightforward and was a learning experience like no other. 
The welcoming atmosphere and clear guidelines make it easy for anyone, regardless of experience level, to jump in and make a difference. And not to forget the satisfaction when your contribution gets accepted and integrated into the project.
It's inspiring to see how a group of passionate individuals can come together to create something truly impactful. 
So, if you've ever thought about contributing to an open-source project, don't hesitate—Uni-notes is the perfect place to start your journey!

**Comment by AhmedThahir** [comment]
Can you check my modified comment?

@Fir121 @ysh1th @bruhvya

**Comment by AhmedThahir** [comment]
Thanks everyone!
