### ISSUE TITLE
Equations not rendering on first load

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#124]
### Project Contribution

- [X] I have read and agree to the project's [Contribution Guidelines](https://github.com/uni-notes/uni-notes/blob/main/contributing_guidlines.md)📜

### What happened?

Equations don't seem to render correctly the first time.

![image](https://github.com/uni-notes/uni-notes/assets/94914628/174977b7-c0fa-4863-a1eb-8cc1c03b203a)

Once reloaded, they render.

### Anything Else🤔?

I suspect there is an issue with latex rendering section. Will investigate this.

**Comment by AhmedThahir** [comment]
Hmmm it only seems to happen on netlify, not on github pages.

**Comment by AhmedThahir** [comment]
> Hmmm it only seems to happen on netlify, not on github pages.

@Fir121 , any idea why?

**Comment by Fir121** [comment]
Unsure will take a look. Does this happen locally? If not it might be some sort of internet issue where it is blocked here (like netlify was for a while)

Can you try with a VPN?

**Comment by AhmedThahir** [comment]
It doesn't happen locally.
It doesn't happen on GitHub Pages.

**Comment by AhmedThahir** [comment]
This issue still exists

**Comment by Fir121** [comment]
I can't seem to replicate this anymore. Is it still happening for you?

**Comment by AhmedThahir** [comment]
Yes, it's still an issue. 

https://uni-notes.netlify.app/CS_Electives/Machine_Learning/03_Model/

First time load

![Screenshot_20241226-205154_Brave](https://github.com/user-attachments/assets/488c79cf-bbc4-4921-902f-a2c5b81c7d7b)

After refreshing

![Screenshot_20241226-205258_Brave](https://github.com/user-attachments/assets/03b144ba-84a7-41b9-84e4-c4207bcf55a0)

**Comment by Fir121** [comment]
Ok so I tried on every browser I have and on data and wifi but this doesn't happen for me. It always looks like the second screenshot.

**Comment by AhmedThahir** [comment]
Ah, it seems to be an issue with my Brave Browser settings. It seems be causing a bug.

Once I disabled all the blocker tools, it works perfectly. 

Apologies for not thinking about this.
