### ISSUE TITLE
Add past year question papers

### ISSUE THREAD

**Issue by Morpheus054** [uni-notes/uni-notes#20]
Suggestion to add past year question papers, specifically the ones which have __answer key__

**Comment by AhmedThahir** [comment]
Pretty good idea.

Whatever question papers we get with answer key, we  could format them in mardown, and upload.

**Comment by ysh1th** [comment]
Would you like to have papers from all years in one place? @AhmedThahir

**Comment by AhmedThahir** [comment]
Meaning?

**Comment by AhmedThahir** [comment]
Okay so for now just put the exam papers of every subject in their corresponding subject folder.

We can re-organize later if required. That's the beauty of working with text files.
