### ISSUE TITLE
Ability to print pages

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#23]
https://www.thoughtco.com/how-to-add-a-print-button-4072006

docs/overrides/main.html

```
{% extends "base.html" %}

{% block content %}

{% if page.url_to_print_page %}
    <a href="{{ page.url_to_print_page }}" title="Print Site" class="md-content__button md-icon">
        {% include ".icons/material/printer.svg" %}
    </a>
{% endif %}

{{ super() }}
{% endblock content %}
```

**Comment by AhmedThahir** [comment]
This is of low priority, so not focusing right now.

**Comment by AhmedThahir** [comment]
Not of high priority, just do if you get time.

**Comment by Fir121** [comment]
This seems unnecessary since most devices have print features built in

**Comment by AhmedThahir** [comment]
I'm saying cuz if someone tries to print from the mobile app they won't be able to.

**Comment by AhmedThahir** [comment]
Bruh my bad (@SivaaB you got competition for fumbling issues)

**Comment by AhmedThahir** [comment]
Closing as not very important. Will resurface if requested again.
