### ISSUE TITLE
Redundancy Reduction

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#29]
Every concept should belong to its fundamental course. Every other course using the same concept should reference that concept from that fundamental course.

- [x] AI
    - [x] Bayes' Theorem can be moved to P&S
- [x] DM & ML

For eg, DM should only have non-ML concepts. ML should have all the ML concepts and DM should reference ML wherever required, just like how DL is doing (haven't uploaded Deep Learning yet, if that's what you're wondering).

Edit: Check the example PR below.

**Comment by Morpheus054** [comment]
@AhmedThahir could you give more clarity with an example?

**Comment by AhmedThahir** [comment]
> @AhmedThahir could you give more clarity with an example?

Check https://github.com/uni-notes/uni-notes/issues/29#issue-1659778005 now

**Comment by Morpheus054** [comment]
Okay got it.

Will try to reference as many topics in AI from other courses.

**Comment by AhmedThahir** [comment]
Yeppp

If you feel like the content of the fundamentals course can be improved using your AI notes, feel free to add it, as I showed.

**Comment by Morpheus054** [comment]
I'm thinking not to delete the entire redundant content.
Instead I'll trim it and then add a reference link to another course. 
Let me know what you think @AhmedThahir

**Comment by AhmedThahir** [comment]
I would recommend keeping the header, but removing the content.

Because if someone is in AI, it is implied they already did P&S course. We just need to instigate them to refer the old notes. 

I'll give you another example

https://uni-notes.netlify.app/2_Core/Data_Structures_%26_Algorithms/13_Graphs/#minimum-spanning-tree

Tell me what you think

**Comment by Morpheus054** [comment]
Okay I'll make the changes accordingly and you can review them.

**Comment by AhmedThahir** [comment]
No hurries, bro. Enjoy the holiday :)

Whatever you did today is more than amazing!!
