### ISSUE TITLE
Share page button not appearing on Desktop browsers

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#30]
There should be a button to share the current page, on the header bar next to theme control.

This is important when people have downloaded as a PWA, as the address bar is no longer available.

**Comment by AhmedThahir** [comment]
Why isn't the button appearing on MacOS Chromium?



![Image](https://user-images.githubusercontent.com/94914628/231261754-3044b048-e3ce-4a4b-9896-3c36adf53098.png)

**Comment by Fir121** [comment]
It is compatible on most Mobile Devices, few browsers have compatibility too you can see the list at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator#browser_compatibility). If you'd like some alternate means for the non compatible pages it is possible but it may look out of place, refer this [codepen](https://codepen.io/ayoisaiah/pen/YbNazJ)

**Comment by AhmedThahir** [comment]
The codepen uses the same logic as yours.

Found the more relevant [compability list](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share) for `navigator.share`

**Comment by Fir121** [comment]
If you view that codepen on an incompatible device you will see the difference.

**Comment by AhmedThahir** [comment]
It works with the same logic as yours, when I updated the codepen.

navigator.share is not supported on my browser.

But I think codepen's engine supports it.

**Comment by AhmedThahir** [comment]
Ahh I got it now!

We can go ahead with this codepen then. I believe a share button is important on all platforms.
