### ISSUE TITLE
Make Contributing Guidelines

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#32]
Could you make a contributing.md file, based on whatever tips and tricks that I've suggested to you guys.

**Comment by ysh1th** [comment]
Sure

**Comment by AhmedThahir** [comment]
@ysh1th Please go through the guidelines and check if I told you any other tips.

https://github.com/uni-notes/uni-notes/blob/main/docs/CONTRIBUTING.md

**Comment by ysh1th** [comment]
All good 👍.
As far as I know, all the tips were included.

**Comment by AhmedThahir** [comment]
Pls add this to how to create a new course. Maybe we can improve. 

@Morpheus054 
@SivaaB 

![Screenshot_20230422-171833_Chrome](https://user-images.githubusercontent.com/94914628/233787566-36d297b9-d656-4c57-adad-c876ef68093c.jpg)
