### ISSUE TITLE
Should we just stick to github pages hosting

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#39]
uni-notes.github.io vs uni-notes.netlify.app

**Comment by SivaaB** [comment]
When it comes to the name I'm a bigger fan of the first one. But, from what I understand GH Page is a good choice for v simple websites -- thinking long term I genuinely feel like **Netlify** would be a better option (netlify deploy previews and what not). 

Some links that may help you decide:- [Reddit](https://www.reddit.com/r/webdev/comments/edldj9/netlify_or_github_pages_for_hosting_a_static/), [Netlify Comparision Chart](https://www.netlify.com/github-pages-vs-netlify/)

**Comment by AhmedThahir** [comment]
Thanks for the links; I just went through them.

Okay you are right, just remembered the benefit of Netlify's deploy preview.
