### ISSUE TITLE
Immunology Notes

### ISSUE THREAD

**Issue by Gurusshitha** [uni-notes/uni-notes#40]
I have made the changes to my notes.

**Comment by AhmedThahir** [comment]
Thankss !!

**Comment by AhmedThahir** [comment]
I've moved it to the taskboard. You may either digitize itself or work with someone else for this.

Also, if you could help find a junior who'd be interested in digitizing your notes, that'd be great.

**Comment by AhmedThahir** [comment]
Hiii @Gurusshitha 
Were you able to find an interested junior?

**Comment by AhmedThahir** [comment]
Biotech students, don't seem to be interested, so I'm closing this for now.

Sorry biotech kids :/
