### ISSUE TITLE
1_Core

### ISSUE THREAD

**Issue by SivaaB** [uni-notes/uni-notes#43]
Hi Firsties, 

To-do checklist for 1_Core: 
- [ ] General Biology notes
- [x] General Chemistry notes 
- [ ] Chem Lab notes [ context: unlike other labs, we don't have demo videos. these notes could be a game changer for compre day ] 

Courses that have been **completed** till midsem, but need to be **updated** post-compre: 
- [x] Computer Programming 
- [x] Engineering Graphics 
- [x] TRW 
- [x] Bio Lab 
- [x] TRW Report

Courses that have been **completed**: 
- [x] Workshop 
- [x] Physics Lab 
- [x] Math I 
- [x] Math II
- [x] Thermodynamics 
- [x] Probability and Statistics 

Edit: adding trw report referencing #60

**Comment by AhmedThahir** [comment]
Great 👍

A good practice is to make task more granular and atomic; you could split each of the above tasks into its own issue.

But if you're comfy with this, this is cool as well. No issues

**Comment by SivaaB** [comment]
Understood, I didn't want to open too many issues for 1_Core as of now and clutter up the dashboard lol, but yes point taken. Will do.

**Comment by SivaaB** [comment]
Understood Thahir, I think I will have to go over all my previous changes once again to make sure it's all in pure markdown. Sorry for the hassle. 

Will refer to the Markdown Tutorial + address issue numbers in future PRs. Will come up with a readme file by the end of the weekend for guidelines, no worries.

**Comment by AhmedThahir** [comment]
Closing this as low priority, and it should theoretically be covered organically by the next batch.

**Comment by AhmedThahir** [comment]
Well done, Sivaa!
