### ISSUE TITLE
Chem Lab notes [ Context : unlike other labs chem lab doesn't have demo videos, which leaves students high and dry to rely on their memory our point here is to make concise notes and upload them ]

### ISSUE THREAD

**Issue by SivaaB** [uni-notes/uni-notes#44]
@AhmedThahir I was poking around accidentally created this, pls delete this issue. Sorry

**Comment by AhmedThahir** [comment]
Wait I'm gonna reopen just to react

Ahahah how does one fumble so bad so as to do this 😭🥰😂
