### ISSUE TITLE
Link to discussions

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#48]
A fresher just told me that she would like a direct link to the discussions page.

https://github.com/uni-notes/uni-notes/discussions/

Should we have one?

**Comment by Fir121** [comment]
What do you mean by direct link?

[https://github.com/uni-notes/uni-notes/discussions](https://github.com/uni-notes/uni-notes/discussions)
This is a direct link.

**Comment by AhmedThahir** [comment]
I meant a direct link from the app to the discussions, like how we have the share button, and repository link.

**Comment by AhmedThahir** [comment]
Okay we can treat this as low priority. We can work on this later.

**Comment by Fir121** [comment]
Maybe it should be added as a tab in the sidebar

**Comment by AhmedThahir** [comment]
What does that mean?

**Comment by Fir121** [comment]
I mean we can add the link here

![image](https://user-images.githubusercontent.com/62911996/232323960-3b12f085-aed9-4cd4-b5ee-c71e3b0beb0a.png)

**Comment by AhmedThahir** [comment]
This is not necessary if we have #61
