### ISSUE TITLE
View Counter

### ISSUE THREAD

**Issue by SivaaB** [uni-notes/uni-notes#58]
Suggestion to add a view counter (like below) on the main page, it would be a really nice way to show how many people this project has helped. What do you guys think? 

![Image](https://user-images.githubusercontent.com/74814237/232226691-08ff37f5-4f63-46e1-895c-96b18d79ad1d.png)

To clarify, it counts the number of times a person has visited the webpage, not exactly the number of "people" lol.

**Comment by AhmedThahir** [comment]
How do we do that?

Do we need to enable analytics for that? I have intentionally disabled analytics cuz that would remove the fun of this. We'll get obsessed with numbers.

**Comment by SivaaB** [comment]
Aha, didn't know about the Google Analytics route, but this idea came from the profile counter on my GitHub Profile. 

You can refer to this [link](https://github.com/arturssmirnovs/github-profile-views-counter) on how it works.

**Comment by Morpheus054** [comment]
You can check this [link](https://www.hitwebcounter.com/)Never used it but I've seen this counter deployed on a website.

**Comment by AhmedThahir** [comment]
Is this very important? 
We could just put an approximate value ourselves, as 50+ or something.

> I have intentionally disabled Google analytics cuz that would remove the fun of this. We'll get obsessed with numbers.

I don't want this to be a pursuit of publicity.

**Comment by SivaaB** [comment]
Aha, okay got it. No worries.

**Comment by AhmedThahir** [comment]
Marking this as low priority, and to be worked on in the future, once all content has been concretely set.
