### ISSUE TITLE
Allow users to comment

### ISSUE THREAD

**Issue by Fir121** [uni-notes/uni-notes#61]
I was working on this and I came across a possibility of commenting in the mkdocs site (like there used to be in the Google drive days), I like this idea because not everyone likes using or knows how to use GitHub to contribute. So commenting is an easier way to to improve quality of content.

**Comment by AhmedThahir** [comment]
Ah yes. This is what those juniors wanted in #48 .

I just thought discussions would be more streamlined.

**Comment by AhmedThahir** [comment]
I think this is it?

https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

**Comment by AhmedThahir** [comment]
Also, if many people comment corrections, won't it be a lot of effort for moderators compared to users directly submitting a PR?

**Comment by AhmedThahir** [comment]
A major thing is that this should be deferred and lazy loaded, to prevent affecting performance.

**Comment by Fir121** [comment]
I did not know that this would require a Github account to comment, that defeats the purpose in my opinion. I will look for any other commenting alternatives.

**Comment by AhmedThahir** [comment]
Okay alright

But this is better than #48

**Comment by Fir121** [comment]
Have looked into it, [this](https://cactus.chat/docs/integrations/mkdocs-material/) might be cool. Unclear if the best means is cactus hosting or self hosting... probably better not to mess with self hosting as that would bring a large amount of dependencies and services.

Let me know if you like it and I can work on this

**Comment by AhmedThahir** [comment]
Will this mean we won't be able to retain our uni-notes site on GitHub?

**Comment by Fir121** [comment]
No no, as long as we use cactus _backend_ for the comments it's ok

If you want self hosted _backend_ only that will have to move. But it's not needed.

Anyway whatever it is, this remains untouched.

**Comment by Fir121** [comment]
Here is a [comments demo](https://cactus.chat/demo/), I have tried it with Uni-Notes and it works pretty well, and everything can be loaded deferred.

BUT there is a fairly major issue, comments sections can be made one of two types. Central comments section (same for all pages), or a unique comment section for each page (more natural). If we go with the second option, it makes reviewing the comments difficult, because as far as I can tell there is no way to review it all in one place.

Also this cactus comments requires an admin account to start using it. As far as I can tell this account is only required as a one time setup and there isn't really anything to be done with it, so it shouldn't be a problem.

**Comment by AhmedThahir** [comment]
Unique comment section for each page would be better. Okay, we can go ahead with the admin account and try it. No harm in doing so.

One question. How would this work changing page names tho. 🤔 If I change the name of a page from "Policies" to "Government Policies", will all the comments stay intact?

**Comment by Fir121** [comment]
Good question, so the comments work on an ID basis, now in the normal use case the ID is manually set on each page of the docs. 

But in our case that is unfeasible, so I will try to use the page path as an ID. So yes if the path (filename) changes, then the comments would change as well. This can be avoided by explicitly adding the ID div in the newly renamed file.

Does this use case occur often? Renaming files?

**Comment by AhmedThahir** [comment]
Renaming files isn't common, but it is possible.

If this is the case, you may add a note in the contributing guidelines that best not to rename a file if it has comments.

**Comment by AhmedThahir** [comment]
Any updates?

**Comment by AhmedThahir** [comment]
Shall we just proceed with this?

https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

**Comment by Fir121** [comment]
Yeah ok I'll make a PR in a couple of weeks, whenever I get time to implement what I wanted to do then I will make a PR for that but for now this will work.

**Comment by AhmedThahir** [comment]
Any updates?

**Comment by AhmedThahir** [comment]
Else, let's try to deconstruct the problem: We want discussions to happen. How it happens is secondary.

Why not add an icon that has a direct link to: https://github.com/uni-notes/uni-notes/discussions/new?category=q-a

**Comment by AhmedThahir** [comment]
Just sharing this as an alternative incase Giscus breaks

https://utteranc.es/
