### ISSUE TITLE
Slow Page Rendering

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#65]
### Project Contribution

- [X] I have read and agree to the project's [Contribution Guidelines](https://github.com/unnamed-project/.github/CODE_OF_CONDUCT.md)📜

### What happened?

Sometimes it seems like the rendering of pages is slow, after clicking a link in the navbar.

https://openlib-cs.acmbpdc.org/ seems much faster. Is it because we have math equations. Should we defer math rendering after the page load?

**Comment by Fir121** [comment]
That seems odd, maybe reconfirm the speed using some online tools. It could be any reason, I think the main slow down of Uni notes is the large content size

But i notice some 404 errors that might be slightly slowing it down maybe fix these.
![image](https://user-images.githubusercontent.com/62911996/234354198-0b1f0166-3f13-458b-b4d5-1fe9ecd15781.png)

**Comment by AhmedThahir** [comment]
Okay noted.

Maybe it's the large navigation menu items that is slowing down the navigation speed through the site (ironic ahahah)

**Comment by Fir121** [comment]
Just a thing to note, openlib.cs does not have instant navigation turned on

**Comment by AhmedThahir** [comment]
Ahh understood. That's probably the difference.

Also, we have a lot more equations and stuff going on. I'll work on optimizing the rendering of equations to only when they are visible.

**Comment by Fir121** [comment]
Has been solved
