### ISSUE TITLE
Create Moderator Guidelines

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#71]
Kindly create guidelines for moderators as well such as: what to verify, politeness, etc.
Doesn't have to perfect; I can improve it

For now, what we're doing is perfect. But in the future, let's say from the upcoming semester, this initiative would move faster if you don't need my approval for everything.

Hence, in the future, as @Fir121 is co-owner, so anything major in the organization/repository, you may contact him.

**Comment by SivaaB** [comment]
[MODERATOR_GUIDELINES.md](https://github.com/uni-notes/uni-notes/files/12060526/MODERATOR_GUIDELINES.md)


Wasn't v sure where this would fit among the other pages. So dropping it here as a file. 
Maybe someone can add on top of this, if felt necessary.

**Comment by AhmedThahir** [comment]
We could just put it in the contributing page; this kinda gives interested people instructions on how to become a moderator. I would prefer this.

However if you feel otherwise, put the contents of the markdown file in discussions, as you rightly said that it may not fit on the other pages, and it may not be really relevant for others.

**Comment by SivaaB** [comment]
Felt right to put it in discussions, done.

**Comment by AhmedThahir** [comment]
Link is #86
