### ISSUE TITLE
Update Contributing Guidelines for Introducing a new course

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#73]
@Morpheus054 please take charge of this. Compile all my relevant comments.

**Comment by AhmedThahir** [comment]
Pls add this to how to create a new course. Maybe we can improve. 

@Morpheus054 
@SivaaB 

![Screenshot_20230422-171833_Chrome](https://user-images.githubusercontent.com/94914628/233787566-36d297b9-d656-4c57-adad-c876ef68093c.jpg)

**Comment by AhmedThahir** [comment]
Bruh come on 😭
@SivaaB @ysh1th y'all team up with @Morpheus054 

I believe in you to figure it out! 😭😂

**Comment by ysh1th** [comment]
Sure, We'll get it done by Thursday 👍🤝

**Comment by SivaaB** [comment]
Probably can mark this as closed, someone has already fixed this [here](https://uni-notes.netlify.app/CONTRIBUTING/#guidelines) under:  "Introducing new Course (or) new notes?"
