### ISSUE TITLE
Show authors of each page

### ISSUE THREAD

**Issue by AhmedThahir** [uni-notes/uni-notes#83]
### Idea Contribution

- [X] I have read and agree to the project's [Contribution Guidelines](https://github.com/unnamed-project/.github/CODE_OF_CONDUCT.md)📜

### What's your idea

I'm thinking it would be nice to show the author of each page. This would give credit to authors and hence incentivize more people to contribute. 

https://github.com/timvink/mkdocs-git-authors-plugin

**Comment by Fir121** [comment]
Looks interesting will work on this and #61 after my PS

**Comment by Fir121** [comment]
Looks easy enough, and the docs also links to a revision date plugin which is also cool. Will do.

**Comment by AhmedThahir** [comment]
Cool! Teach me also.
