### ISSUE TITLE
Eliminate Warnings during mkdocs serve

### ISSUE THREAD

**Issue by Fir121** [uni-notes/uni-notes#88]
### Idea Contribution

- [X] I have read and agree to the project's [Contribution Guidelines](https://github.com/unnamed-project/.github/CODE_OF_CONDUCT.md)📜

### What's your idea

Running `mkdocs serve` or `mkdocs build` brings a large amount of warnings, looks like dead links, bad files, deprecation warnings and the like. I hope this can be eliminated. This might also make the build process quicker helping for faster testing.

**Comment by AhmedThahir** [comment]
Okay I will look into this.

**Comment by AhmedThahir** [comment]
@SivaaB @ysh1th 

> dead links, bad files, deprecation warnings

Firstly, let me know what links are broken.

**Comment by Fir121** [comment]
A lot of these links give a 404 -> https://uni-notes.netlify.app/1_Core/Bio_Lab/

**Comment by ysh1th** [comment]
It's possible that the file's location was changed.

@SivaaB maybe updating the links from your Drive would solve the issue.

**Comment by SivaaB** [comment]
Ah dammit yes, that entire [page](https://uni-notes.netlify.app/1_Core/Bio_Lab/)  was GDrive links from Google Classroom. 
Guess the profs removed it post-compre. I should've downloaded those videos and saved a copy on my GDrive. Rest assured I'll do the same next sem when juniors come in and the classroom links are active again.

Don't worry this is not the case for other Lab Videos like [Mech Workshop](https://uni-notes.netlify.app/1_core/workshop/lab/) and [Physics Lab](https://uni-notes.netlify.app/1_core/physics_lab/) which are completely fine.

**Comment by AhmedThahir** [comment]
Okay if it's identitied, please fix it as soon as possible. @SivaaB 

This is in line with #78

**Comment by AhmedThahir** [comment]
Hey guys, please perform the check now.
